Update dev_infra.yml

diff --git a/Terraform-app-nodesjs-infa/dev_infra.yml b/Terraform-app-nodesjs-infa/dev_infra.yml
--- a/Terraform-app-nodesjs-infa/dev_infra.yml
+++ b/Terraform-app-nodesjs-infa/dev_infra.yml
@@ -1,3 +1,4 @@
+
 name: Dev env infra
 
 on:
@@ -41,11 +42,17 @@ jobs:
         id: plan
         run: |
           set -o pipefail
-          terraform -chdir=env/dev plan -input=false -var-file="dev.tfvars" -out=tfplan-${{ github.run_id }}.tfplan | tee /dev/sterr
+          terraform -chdir=env/dev plan -input=false -var-file="dev.tfvars" -out=tfplan-${{ github.run_id }}.tfplan -detailed-exitcode || exit_code=$?
+          if [ "${exit_code:-0}" != "0" ] && [ "${exit_code:-0}" != "2" ]; then
+             echo "Terraform plan failed!"
+             exit $exit_code
+          fi
           terraform show -no-color tfplan-${{ github.run_id }}.tfplan > env/dev/tfplan-${{ github.run_id }}.tfplan
+        #  terraform -chdir=env/dev plan -input=false -var-file="dev.tfvars" -out=tfplan-${{ github.run_id }}.tfplan | tee /dev/sterr
+     
 
       - name: iploaf terraform plan artifact
-        uses: actions/upload-artifacts@v3
+        uses: actions/upload-artifact@v4
         with: 
            name: terraform-plan-dev-${{ github.run_id }}
            path: env/dev/tfplan-${{ github.run_id }}.tfplan
